解决错误： Potentially incompatible change required to top-level dependency
While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: gwendall:simple-schema-i18n 0.2.3, was
   0.3.0.
   Constraints on package "gwendall:simple-schema-i18n":

   To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update
   on the command line.